
services:
  db:
    image: mysql:8
    container_name: diario_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - diario-net

  backend:
    build: .
    container_name: diario_backend
    command: ["/app/wait-for-db.sh", "${MYSQL_HOST}:${MYSQL_PORT}", "uvicorn", "main:app", "--host", "${APP_HOST}", "--port", "${APP_PORT}", "--reload"]
    ports:
        - "${APP_PORT}:${APP_PORT}"
    environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DB: ${MYSQL_DB}
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_PORT: ${MYSQL_PORT}
        SECRET_KEY: ${SECRET_KEY}
    depends_on:
        - db
    volumes:
        - .:/app
    networks:
        - diario-net


volumes:
  mysql-data:

networks:
  diario-net:
    driver: bridge
