[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "W"]  # regras do Flake8 + warnings
ignore = ["E501"]         # exemplo: ignora linhas longas

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
